package main

// Language represents a programming language with its comment patterns
type Language struct {
	Name              string
	Extensions        []string
	SingleLineComment string
	MultiLineStart    string
	MultiLineEnd      string
	StringDelimiters  []string
	NestedComments    bool
}

// Languages defines all supported programming languages and their comment patterns
var Languages = map[string]*Language{
	".go": {
		Name:              "Go",
		Extensions:        []string{".go"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
		StringDelimiters:  []string{"\"", "`"},
	},
	".js": {
		Name:              "JavaScript",
		Extensions:        []string{".js"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
		StringDelimiters:  []string{"\"", "'", "`"},
	},
	".ts": {
		Name:              "TypeScript",
		Extensions:        []string{".ts"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
		StringDelimiters:  []string{"\"", "'", "`"},
	},
	".tsx": {
		Name:              "TypeScript JSX",
		Extensions:        []string{".tsx"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".jsx": {
		Name:              "JavaScript JSX",
		Extensions:        []string{".jsx"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".html": {
		Name:              "HTML",
		Extensions:        []string{".html", ".htm"},
		SingleLineComment: "",
		MultiLineStart:    "<!--",
		MultiLineEnd:      "-->",
	},
	".htm": {
		Name:              "HTML",
		Extensions:        []string{".html", ".htm"},
		SingleLineComment: "",
		MultiLineStart:    "<!--",
		MultiLineEnd:      "-->",
	},
	".py": {
		Name:              "Python",
		Extensions:        []string{".py"},
		SingleLineComment: "#",
		MultiLineStart:    `"""`,
		MultiLineEnd:      `"""`,
		StringDelimiters:  []string{"\"", "'"},
	},
	".rb": {
		Name:              "Ruby",
		Extensions:        []string{".rb"},
		SingleLineComment: "#",
		MultiLineStart:    "=begin",
		MultiLineEnd:      "=end",
		StringDelimiters:  []string{"\"", "'"},
	},
	".java": {
		Name:              "Java",
		Extensions:        []string{".java"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
		StringDelimiters:  []string{"\"", "'"},
	},
	".c": {
		Name:              "C",
		Extensions:        []string{".c"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
		StringDelimiters:  []string{"\"", "'"},
	},
	".h": {
		Name:              "C Header",
		Extensions:        []string{".h"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
		StringDelimiters:  []string{"\"", "'"},
	},
	".cpp": {
		Name:              "C++",
		Extensions:        []string{".cpp", ".cc", ".cxx"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
		StringDelimiters:  []string{"\"", "'"},
	},
	".cc": {
		Name:              "C++",
		Extensions:        []string{".cpp", ".cc", ".cxx"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
		StringDelimiters:  []string{"\"", "'"},
	},
	".hpp": {
		Name:              "C++ Header",
		Extensions:        []string{".hpp"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
		StringDelimiters:  []string{"\"", "'"},
	},
	".cs": {
		Name:              "C#",
		Extensions:        []string{".cs"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
		StringDelimiters:  []string{"\"", "'"},
	},
	".php": {
		Name:              "PHP",
		Extensions:        []string{".php"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
		StringDelimiters:  []string{"\"", "'"},
	},
	".swift": {
		Name:              "Swift",
		Extensions:        []string{".swift"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
		StringDelimiters:  []string{"\""},
		NestedComments:    true,
	},
	".kt": {
		Name:              "Kotlin",
		Extensions:        []string{".kt"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
		StringDelimiters:  []string{"\""},
		NestedComments:    true,
	},
	".rs": {
		Name:              "Rust",
		Extensions:        []string{".rs"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
		StringDelimiters:  []string{"\""},
		NestedComments:    true,
	},
	".scala": {
		Name:              "Scala",
		Extensions:        []string{".scala"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
		StringDelimiters:  []string{"\"", "'"},
	},
	".json": {
		Name:              "JSON",
		Extensions:        []string{".json"},
		SingleLineComment: "",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".yaml": {
		Name:              "YAML",
		Extensions:        []string{".yaml", ".yml"},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".yml": {
		Name:              "YAML",
		Extensions:        []string{".yaml", ".yml"},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".md": {
		Name:              "Markdown",
		Extensions:        []string{".md"},
		SingleLineComment: "",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".css": {
		Name:              "CSS",
		Extensions:        []string{".css"},
		SingleLineComment: "",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".scss": {
		Name:              "SCSS",
		Extensions:        []string{".scss"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".sass": {
		Name:              "Sass",
		Extensions:        []string{".sass"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".less": {
		Name:              "Less",
		Extensions:        []string{".less"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".sql": {
		Name:              "SQL",
		Extensions:        []string{".sql"},
		SingleLineComment: "--",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".sh": {
		Name:              "Shell",
		Extensions:        []string{".sh", ".bash"},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".bash": {
		Name:              "Shell",
		Extensions:        []string{".sh", ".bash"},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".xml": {
		Name:              "XML",
		Extensions:        []string{".xml"},
		SingleLineComment: "",
		MultiLineStart:    "<!--",
		MultiLineEnd:      "-->",
	},
	".vue": {
		Name:              "Vue",
		Extensions:        []string{".vue"},
		SingleLineComment: "//",
		MultiLineStart:    "<!--",
		MultiLineEnd:      "-->",
	},
	".svelte": {
		Name:              "Svelte",
		Extensions:        []string{".svelte"},
		SingleLineComment: "//",
		MultiLineStart:    "<!--",
		MultiLineEnd:      "-->",
	},
	".lua": {
		Name:              "Lua",
		Extensions:        []string{".lua"},
		SingleLineComment: "--",
		MultiLineStart:    "--[[",
		MultiLineEnd:      "]]",
	},
	".r": {
		Name:              "R",
		Extensions:        []string{".r", ".R"},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".R": {
		Name:              "R",
		Extensions:        []string{".r", ".R"},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".pl": {
		Name:              "Perl",
		Extensions:        []string{".pl", ".pm"},
		SingleLineComment: "#",
		MultiLineStart:    "=pod",
		MultiLineEnd:      "=cut",
	},
	".pm": {
		Name:              "Perl",
		Extensions:        []string{".pl", ".pm"},
		SingleLineComment: "#",
		MultiLineStart:    "=pod",
		MultiLineEnd:      "=cut",
	},
	".ex": {
		Name:              "Elixir",
		Extensions:        []string{".ex", ".exs"},
		SingleLineComment: "#",
		MultiLineStart:    `"""`,
		MultiLineEnd:      `"""`,
	},
	".exs": {
		Name:              "Elixir",
		Extensions:        []string{".ex", ".exs"},
		SingleLineComment: "#",
		MultiLineStart:    `"""`,
		MultiLineEnd:      `"""`,
	},
	".erl": {
		Name:              "Erlang",
		Extensions:        []string{".erl"},
		SingleLineComment: "%",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".hs": {
		Name:              "Haskell",
		Extensions:        []string{".hs"},
		SingleLineComment: "--",
		MultiLineStart:    "{-",
		MultiLineEnd:      "-}",
	},
	".clj": {
		Name:              "Clojure",
		Extensions:        []string{".clj"},
		SingleLineComment: ";",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".toml": {
		Name:              "TOML",
		Extensions:        []string{".toml"},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".ini": {
		Name:              "INI",
		Extensions:        []string{".ini"},
		SingleLineComment: ";",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".dockerfile": {
		Name:              "Dockerfile",
		Extensions:        []string{".dockerfile"},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".makefile": {
		Name:              "Makefile",
		Extensions:        []string{".makefile"},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".tf": {
		Name:              "Terraform",
		Extensions:        []string{".tf"},
		SingleLineComment: "#",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".proto": {
		Name:              "Protocol Buffers",
		Extensions:        []string{".proto"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".graphql": {
		Name:              "GraphQL",
		Extensions:        []string{".graphql", ".gql"},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".gql": {
		Name:              "GraphQL",
		Extensions:        []string{".graphql", ".gql"},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".txt": {
		Name:              "Text",
		Extensions:        []string{".txt"},
		SingleLineComment: "",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".hcl": {
		Name:              "HCL",
		Extensions:        []string{".hcl"},
		SingleLineComment: "#",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".y": {
		Name:              "Yacc",
		Extensions:        []string{".y"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".nix": {
		Name:              "Nix",
		Extensions:        []string{".nix"},
		SingleLineComment: "#",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".json5": {
		Name:              "JSON5",
		Extensions:        []string{".json5"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".s": {
		Name:              "Assembly",
		Extensions:        []string{".s", ".S", ".asm"},
		SingleLineComment: ";",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".S": {
		Name:              "Assembly",
		Extensions:        []string{".s", ".S", ".asm"},
		SingleLineComment: ";",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".asm": {
		Name:              "Assembly",
		Extensions:        []string{".s", ".S", ".asm"},
		SingleLineComment: ";",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".dart": {
		Name:              "Dart",
		Extensions:        []string{".dart"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
		StringDelimiters:  []string{"\"", "'"},
	},
	".groovy": {
		Name:              "Groovy",
		Extensions:        []string{".groovy"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
		StringDelimiters:  []string{"\"", "'"},
	},
	".jl": {
		Name:              "Julia",
		Extensions:        []string{".jl"},
		SingleLineComment: "#",
		MultiLineStart:    "#=",
		MultiLineEnd:      "=#",
		StringDelimiters:  []string{"\"", "'"},
	},
	".coffee": {
		Name:              "CoffeeScript",
		Extensions:        []string{".coffee"},
		SingleLineComment: "#",
		MultiLineStart:    "###",
		MultiLineEnd:      "###",
		StringDelimiters:  []string{"\"", "'", "`"},
	},
	".pug": {
		Name:              "Pug",
		Extensions:        []string{".pug"},
		SingleLineComment: "//",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".jade": {
		Name:              "Jade",
		Extensions:        []string{".jade"},
		SingleLineComment: "//",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".twig": {
		Name:              "Twig",
		Extensions:        []string{".twig"},
		SingleLineComment: "{#",
		MultiLineStart:    "{#",
		MultiLineEnd:      "#}",
	},
	".ejs": {
		Name:              "EJS",
		Extensions:        []string{".ejs"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".haml": {
		Name:              "Haml",
		Extensions:        []string{".haml"},
		SingleLineComment: "-#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".tsv": {
		Name:              "TSV",
		Extensions:        []string{".tsv"},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".csv": {
		Name:              "CSV",
		Extensions:        []string{".csv"},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".awk": {
		Name:              "AWK",
		Extensions:        []string{".awk"},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".sed": {
		Name:              "Sed",
		Extensions:        []string{".sed"},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".v": {
		Name:              "V",
		Extensions:        []string{".v"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".zig": {
		Name:              "Zig",
		Extensions:        []string{".zig"},
		SingleLineComment: "//",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".ada": {
		Name:              "Ada",
		Extensions:        []string{".ada", ".adb", ".ads"},
		SingleLineComment: "--",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".adb": {
		Name:              "Ada",
		Extensions:        []string{".ada", ".adb", ".ads"},
		SingleLineComment: "--",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".ml": {
		Name:              "OCaml",
		Extensions:        []string{".ml"},
		SingleLineComment: "(*",
		MultiLineEnd:      "*)",
		MultiLineStart:    "(*",
	},
	".mli": {
		Name:              "OCaml Interface",
		Extensions:        []string{".mli"},
		SingleLineComment: "(*",
		MultiLineEnd:      "*)",
		MultiLineStart:    "(*",
	},
	".fs": {
		Name:              "F#",
		Extensions:        []string{".fs", ".fsx", ".fsi"},
		SingleLineComment: "//",
		MultiLineStart:    "(*",
		MultiLineEnd:      "*)",
	},
	".fsx": {
		Name:              "F# Script",
		Extensions:        []string{".fs", ".fsx", ".fsi"},
		SingleLineComment: "//",
		MultiLineStart:    "(*",
		MultiLineEnd:      "*)",
	},
	".nim": {
		Name:              "Nim",
		Extensions:        []string{".nim"},
		SingleLineComment: "#",
		MultiLineStart:    "#[",
		MultiLineEnd:      "]#",
	},
	".d": {
		Name:              "D",
		Extensions:        []string{".d"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".pas": {
		Name:              "Pascal",
		Extensions:        []string{".pas"},
		SingleLineComment: "//",
		MultiLineStart:    "(*",
		MultiLineEnd:      "*)",
	},
	".vb": {
		Name:              "Visual Basic",
		Extensions:        []string{".vb"},
		SingleLineComment: "'",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".vbs": {
		Name:              "VBScript",
		Extensions:        []string{".vbs"},
		SingleLineComment: "'",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".ps1": {
		Name:              "PowerShell",
		Extensions:        []string{".ps1"},
		SingleLineComment: "#",
		MultiLineStart:    "<#",
		MultiLineEnd:      "#>",
	},
	".asmx": {
		Name:              "ASP.NET",
		Extensions:        []string{".asmx"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".aspx": {
		Name:              "ASP.NET",
		Extensions:        []string{".aspx"},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".cshtml": {
		Name:              "Razor",
		Extensions:        []string{".cshtml"},
		SingleLineComment: "@*",
		MultiLineStart:    "@*",
		MultiLineEnd:      "*@",
	},
	".vbhtml": {
		Name:              "Razor VB",
		Extensions:        []string{".vbhtml"},
		SingleLineComment: "@*",
		MultiLineStart:    "@*",
		MultiLineEnd:      "*@",
	},
}

// BinaryExtensions contains file extensions that should be skipped
var BinaryExtensions = map[string]bool{
	// Images
	".jpg":  true,
	".jpeg": true,
	".png":  true,
	".gif":  true,
	".bmp":  true,
	".ico":  true,
	".svg":  true,
	".webp": true,
	".tiff": true,
	".tif":  true,
	".psd":  true,
	".raw":  true,
	".heif": true,
	".heic": true,
	".avif": true,

	// Documents
	".pdf":  true,
	".doc":  true,
	".docx": true,
	".xls":  true,
	".xlsx": true,
	".ppt":  true,
	".pptx": true,
	".odt":  true,
	".ods":  true,
	".odp":  true,
	".rtf":  true,
	".epub": true,
	".mobi": true,

	// Archives
	".zip":  true,
	".tar":  true,
	".gz":   true,
	".tgz":  true,
	".bz2":  true,
	".xz":   true,
	".lz":   true,
	".lzma": true,
	".rar":  true,
	".7z":   true,
	".cab":  true,
	".iso":  true,
	".dmg":  true,
	".deb":  true,
	".rpm":  true,
	".apk":  true,
	".msi":  true,

	// Executables and libraries
	".exe":   true,
	".dll":   true,
	".so":    true,
	".dylib": true,
	".bin":   true,
	".com":   true,
	".mach":  true,
	".elf":   true,

	// Data files
	".dat":     true,
	".db":      true,
	".sqlite":  true,
	".sqlite3": true,
	".mdb":     true,
	".accdb":   true,
	".frm":     true,
	".ibd":     true,
	".dbf":     true,

	// Audio
	".mp3":  true,
	".wav":  true,
	".flac": true,
	".ogg":  true,
	".aac":  true,
	".wma":  true,
	".m4a":  true,
	".aiff": true,
	".mid":  true,
	".midi": true,

	// Video
	".mp4":  true,
	".avi":  true,
	".mov":  true,
	".wmv":  true,
	".flv":  true,
	".mkv":  true,
	".webm": true,
	".m4v":  true,
	".mpeg": true,
	".mpg":  true,
	".3gp":  true,

	// Fonts
	".ttf":   true,
	".otf":   true,
	".woff":  true,
	".woff2": true,
	".eot":   true,
	".fon":   true,

	// Compiled/bytecode
	".class":   true,
	".jar":     true,
	".war":     true,
	".ear":     true,
	".aar":     true,
	".ipa":     true,
	".app":     true,
	".sys":     true,
	".drv":     true,
	".ko":      true,
	".vxd":     true,
	".ocx":     true,
	".pyc":     true,
	".pyo":     true,
	".pyd":     true,
	".elc":     true,
	".hi":      true,
	".o":       true,
	".obj":     true,
	".ilk":     true,
	".pdb":     true,
	".idb":     true,
	".exp":     true,
	".lib":     true,
	".a":       true,
	".la":      true,
	".lo":      true,
	".mod":     true,
	".symvers": true,
	".order":   true,
	".build":   true,
	// Lock files (often auto-generated)
	".lock": true,

	// Node.js specific
	".node": true,

	// Office documents
	".pages":   true,
	".numbers": true,
	".key":     true,
	".keynote": true,
	".indd":    true,
	".ai":      true,
	".eps":     true,
	".sketch":  true,
	".fig":     true,
	".xd":      true,

	// Game and multimedia files
	".unity":        true,
	".unitypackage": true,
	".uasset":       true,
	".umap":         true,
	".blend":        true,
	".blend1":       true,
	".ma":           true,
	".mb":           true,
	".max":          true,
	".c4d":          true,
	".fbx":          true,
	".3ds":          true,
	".stl":          true,
	".dae":          true,
	".gltf":         true,
	".glb":          true,
	".ply":          true,
	".wrl":          true,
	".x3d":          true,
	".usd":          true,
	".usda":         true,
	".usdc":         true,
	".usdz":         true,

	// System and virtual machine files
	".vmdk":  true,
	".vhd":   true,
	".vhdx":  true,
	".qcow2": true,
	".vdi":   true,
	".ova":   true,
	".ovf":   true,
	".nvram": true,
	".vmsn":  true,
	".vmem":  true,
	".vmss":  true,
	".vswp":  true,
	".vmx":   true,
	".vmxf":  true,
	".pvm":   true,
	".hdd":   true,
	".sub":   true,

	// Database files
	".mdf":  true,
	".ldf":  true,
	".ndf":  true,
	".bak":  true,
	".trn":  true,
	".myd":  true,
	".myi":  true,
	".db3":  true,
	".sdb":  true,
	".s3db": true,
	".sl3":  true,

	// Email and communication files
	".pst":   true,
	".ost":   true,
	".msg":   true,
	".eml":   true,
	".emlx":  true,
	".mbx":   true,
	".mbox":  true,
	".vcf":   true,
	".vcard": true,

	// Backup and temporary files
	".tmp":        true,
	".temp":       true,
	".swp":        true,
	".swo":        true,
	".backup":     true,
	".old":        true,
	".save":       true,
	".sav":        true,
	".cache":      true,
	".part":       true,
	".crdownload": true,
	".download":   true,
	".partial":    true,
	".aria2":      true,

	// Security and certificate files
	".p12":        true,
	".pfx":        true,
	".pem":        true,
	".crt":        true,
	".cer":        true,
	".der":        true,
	".jks":        true,
	".keystore":   true,
	".truststore": true,
	".gpg":        true,
	".pgp":        true,
	".asc":        true,
	".sig":        true,

	// Other binary formats
	".hex":      true,
	".rom":      true,
	".img":      true,
	".toast":    true,
	".vcd":      true,
	".nrg":      true,
	".mds":      true,
	".ccd":      true,
	".cue":      true,
	".ecm":      true,
	".ape":      true,
	".tta":      true,
	".dts":      true,
	".thd":      true,
	".mlp":      true,
	".amr":      true,
	".3ga":      true,
	".mxmf":     true,
	".imy":      true,
	".awb":      true,
	".qcp":      true,
	".dvf":      true,
	".msv":      true,
	".ra":       true,
	".rm":       true,
	".ram":      true,
	".smi":      true,
	".smil":     true,
	".xap":      true,
	".jad":      true,
	".sis":      true,
	".sisx":     true,
	".prc":      true,
	".azw":      true,
	".azw3":     true,
	".kfx":      true,
	".lit":      true,
	".fb2":      true,
	".fb2.zip":  true,
	".lrf":      true,
	".lrx":      true,
	".baf":      true,
	".zno":      true,
	".tr2":      true,
	".tr3":      true,
	".pdc":      true,
	".xeb":      true,
	".ceb":      true,
	".pkg":      true,
	".xpi":      true,
	".crx":      true,
	".oex":      true,
	".nex":      true,
	".mxp":      true,
	".air":      true,
	".widget":   true,
	".wgt":      true,
	".dmp":      true,
	".hprof":    true,
	".heapdump": true,
	".core":     true,
	".minidump": true,
	".mdmp":     true,
	".wer":      true,
	".etl":      true,
	".evtx":     true,
	".evt":      true,
}

// FilenameLanguages maps specific filenames (without extension) to languages
var FilenameLanguages = map[string]*Language{
	"Makefile": {
		Name:              "Makefile",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"makefile": {
		Name:              "Makefile",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"GNUmakefile": {
		Name:              "Makefile",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"Dockerfile": {
		Name:              "Dockerfile",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"dockerfile": {
		Name:              "Dockerfile",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"LICENSE": {
		Name:              "License",
		Extensions:        []string{},
		SingleLineComment: "",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"LICENSE.txt": {
		Name:              "License",
		Extensions:        []string{},
		SingleLineComment: "",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"LICENSE.md": {
		Name:              "License",
		Extensions:        []string{},
		SingleLineComment: "",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"LICENCE": {
		Name:              "License",
		Extensions:        []string{},
		SingleLineComment: "",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"COPYING": {
		Name:              "License",
		Extensions:        []string{},
		SingleLineComment: "",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"README": {
		Name:              "Readme",
		Extensions:        []string{},
		SingleLineComment: "",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"README.txt": {
		Name:              "Readme",
		Extensions:        []string{},
		SingleLineComment: "",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"Vagrantfile": {
		Name:              "Vagrantfile",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "=begin",
		MultiLineEnd:      "=end",
	},
	"Gemfile": {
		Name:              "Gemfile",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "=begin",
		MultiLineEnd:      "=end",
	},
	"Rakefile": {
		Name:              "Rakefile",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "=begin",
		MultiLineEnd:      "=end",
	},
	"Procfile": {
		Name:              "Procfile",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"CMakeLists.txt": {
		Name:              "CMake",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"Jenkinsfile": {
		Name:              "Jenkinsfile",
		Extensions:        []string{},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	"CHANGELOG": {
		Name:              "Changelog",
		Extensions:        []string{},
		SingleLineComment: "",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"CHANGELOG.md": {
		Name:              "Changelog",
		Extensions:        []string{},
		SingleLineComment: "",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"AUTHORS": {
		Name:              "Authors",
		Extensions:        []string{},
		SingleLineComment: "",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"CONTRIBUTORS": {
		Name:              "Contributors",
		Extensions:        []string{},
		SingleLineComment: "",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"build.gradle": {
		Name:              "Gradle",
		Extensions:        []string{},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	"build.gradle.kts": {
		Name:              "Gradle Kotlin",
		Extensions:        []string{},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	"gradlew": {
		Name:              "Shell Script",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"gradlew.bat": {
		Name:              "Batch File",
		Extensions:        []string{},
		SingleLineComment: "REM",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"mvnw": {
		Name:              "Shell Script",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"mvnw.cmd": {
		Name:              "Batch File",
		Extensions:        []string{},
		SingleLineComment: "REM",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"pom.xml": {
		Name:              "Maven POM",
		Extensions:        []string{},
		SingleLineComment: "",
		MultiLineStart:    "<!--",
		MultiLineEnd:      "-->",
	},
	"composer.json": {
		Name:              "Composer",
		Extensions:        []string{},
		SingleLineComment: "",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"package.json": {
		Name:              "NPM Package",
		Extensions:        []string{},
		SingleLineComment: "",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"tsconfig.json": {
		Name:              "TypeScript Config",
		Extensions:        []string{},
		SingleLineComment: "",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	"webpack.config.js": {
		Name:              "Webpack Config",
		Extensions:        []string{},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	"gruntfile.js": {
		Name:              "Grunt",
		Extensions:        []string{},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	"gulpfile.js": {
		Name:              "Gulp",
		Extensions:        []string{},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
}

// HiddenFileLanguages maps hidden config files to languages
var HiddenFileLanguages = map[string]*Language{
	".gitignore": {
		Name:              "Git Config",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".gitattributes": {
		Name:              "Git Config",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".dockerignore": {
		Name:              "Docker Config",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".editorconfig": {
		Name:              "EditorConfig",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".eslintrc": {
		Name:              "ESLint Config",
		Extensions:        []string{},
		SingleLineComment: "//",
		MultiLineStart:    "/*",
		MultiLineEnd:      "*/",
	},
	".prettierrc": {
		Name:              "Prettier Config",
		Extensions:        []string{},
		SingleLineComment: "",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".babelrc": {
		Name:              "Babel Config",
		Extensions:        []string{},
		SingleLineComment: "",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".npmrc": {
		Name:              "NPM Config",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".yarnrc": {
		Name:              "Yarn Config",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".env": {
		Name:              "Environment",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".env.example": {
		Name:              "Environment",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".env.local": {
		Name:              "Environment",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".htaccess": {
		Name:              "Apache Config",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
	".travis.yml": {
		Name:              "Travis CI",
		Extensions:        []string{},
		SingleLineComment: "#",
		MultiLineStart:    "",
		MultiLineEnd:      "",
	},
}

// GetLanguage returns the language definition for a given file extension
func GetLanguage(ext string) *Language {
	if lang, ok := Languages[ext]; ok {
		return lang
	}
	return nil
}

// GetLanguageByFilename returns the language definition for a specific filename
func GetLanguageByFilename(filename string) *Language {
	// Check exact filename match first
	if lang, ok := FilenameLanguages[filename]; ok {
		return lang
	}
	// Check hidden file languages
	if lang, ok := HiddenFileLanguages[filename]; ok {
		return lang
	}
	return nil
}

// IsBinaryExtension checks if the file extension is a binary file
func IsBinaryExtension(ext string) bool {
	return BinaryExtensions[ext]
}
